version: '3'
services:
  app:
    image: node:18.18.2-slim
    container_name: hsr_display
    volumes:
      - ./:/app
    working_dir: /app
    tty: true
    command: >
      bash -c "npm install && npm run dev"
    ports:
      - "3000:3000"
